version: 1.0.{build}
os: Visual Studio 2015

install:
  - ps: (new-object Net.WebClient).DownloadString("https://raw.github.com/madskristensen/ExtensionScripts/master/AppVeyor/vsix.ps1") | iex

before_build:
  - ps: Vsix-IncrementVsixVersion | Vsix-UpdateBuildVersion
  - ps: Vsix-TokenReplacement src\HlslTools.VisualStudio\HlslToolsPackage.cs 'Version = "([0-9\\.]+)"' 'Version = "{version}"'
  - ps: Vsix-TokenReplacement src\HlslTools\Parser\HlslParser.cs 'Version = "([0-9\\.]+)"' 'Version = "{version}"'

build_script:
  - nuget restore src/HlslTools.sln -Verbosity quiet
  - msbuild src/HlslTools.sln /p:configuration=Release /p:DeployExtension=false /p:ZipPackageCompressionLevel=normal /v:m

test_script:
  - nunit-console src/HlslTools.Tests/bin/Release/HlslTools.Tests.dll
  - nunit-console-x86 src/HlslTools.VisualStudio.Tests/bin/Release/HlslTools.VisualStudio.Tests.dll

after_test:
  - ps: Vsix-PushArtifacts | Vsix-PublishToGallery