trigger:
- master

pr:
- master

variables:
  solution: 'src/ShaderTools.sln'
  buildConfiguration: 'Release'

jobs:

- job: HlslTools_Build_Test
  
  strategy:
    maxParallel: 2
    matrix:
      VS2017:
        imageName: 'vs2017-win2016'
        _name: VS2017
      VS2019:
        imageName: 'windows-2019'
        _name: VS2019
  
  pool:
    vmImage: $(imageName)
  
  steps:
  
  - task: UseDotNet@2
    displayName: 'Install .NET Core 3.0'
    inputs:
      packageType: sdk
      version: 3.x
      includePreviewVersions: true

  - task: NuGetCommand@2
    displayName: 'Restore NuGet Packages'
    inputs:
      restoreSolution: '$(solution)'
  
  - task: VSBuild@1
    displayName: 'Build'
    inputs:
      solution: '$(solution)'
      configuration: $(buildConfiguration)

  - task: DotNetCoreCLI@2
    displayName: Tests
    inputs:
      command: test
      projects: '**/*Tests/*.csproj'
      arguments: '--configuration $(buildConfiguration)'